name: Daily Tasks CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Step
        run: echo "Build done:repository checked out and ready"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Step
        run: |
          echo "Running tests..."
          if [ -f tasks.txt ]; then
            echo "Test Passed: tasks.txt exists!"
          else
            echo "Test Failed: tasks.txt missing!"
            exit 1
          fi

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}   # Use PAT here
          publish_dir: ./   # deploy root folder

